### ISSUE TITLE
Connect the DynamoDB to our skill (Week 4)

### ISSUE THREAD

**Issue by wes-yang** [skl1m/ecopal#11]
Be able to make a query to our database

**Comment by skl1m** [comment]
Instructions for how to get started to use NodeJS and dynamoDB locally on your computer:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.html

1. Download and run DynamoDB on your computer.  
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html

2. Set up an AWS access key to use the AWS SDKs.
3. Set up the AWS SDK for JavaScript:
          Go to http://nodejs.org and install Node.js.
          Go to https://aws.amazon.com/sdk-for-node-js and install the AWS SDK for 
          JavaScript.
https://www.youtube.com/watch?v=EBlHUDUfCfk
https://medium.com/@Keithweaver_/using-aws-dynamodb-using-node-js-fd17cf1724e0


Allocated Time : 18 Hours

**Comment by skl1m** [comment]
To have dynamoDB locally using terminal on Mac
https://medium.com/@kaberi.basu25/getting-started-with-dynamodb-in-mac-9dcedc1efe90

**Comment by skl1m** [comment]
After testing in order to set up the web service: 
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SettingUp.DynamoWebService.html

**Comment by skl1m** [comment]
Ended up not going with this route mentioned above.
