### ISSUE TITLE
Connect the website to the database and make a request (Week 6)

### ISSUE THREAD

**Issue by wes-yang** [skl1m/ecopal#17]
The webpage can make queries to dynamoDB and display the information

**Comment by mdpatel4** [comment]
https://www.youtube.com/watch?v=Byhg9BBsbJw

**Comment by mdpatel4** [comment]
able to request one row at a time, continue working on requesting multiple rows from DynamoDB.

**Comment by mdpatel4** [comment]
Below link help me with cross configuration for s3 bucket, which gives me access to connect with API Gate way to read data from dynamoDB through Lambda function.

https://aws.amazon.com/blogs/aws/developer-preview-aws-sdk-for-javascript/

**Comment by mdpatel4** [comment]
Provide me basic Idea of IAM Role Policy and connectivity between each layer.

https://aws.amazon.com/blogs/startups/dynamic-websites-using-the-aws-sdk-for-javascript-in-the-browser/

**Comment by mdpatel4** [comment]
Give me a basic Idea of reading all values from DynamoDB to Lambda function. Also, give me a idea of differentiating values by location, like read only information for sustainability at home.  And print only one attribute value from table.

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.04.html

**Comment by mdpatel4** [comment]
Finally able to read data from DynamoDB from website. Below link was our test version, in which leader ship board provides my dummy data from DynamoDB, and sustainability at home option provide dummy data from DynamoDB as well.

This link is s3 bucket static web hosting link.

ec0pal.s3-website-us-east-1.amazonaws.com
