### ISSUE TITLE
Work on implementation of website and finalize website design and content (Week 7)

### ISSUE THREAD

**Issue by wes-yang** [skl1m/ecopal#19]
Have at least 70% of the pages working and finish editing HTML and CSS of each page

**Comment by wes-yang** [comment]
Finished HTML and CSS files for all the static pages including: About Us, Developer Guide, User Guide, Homepage, and Contact Us

**Comment by mdpatel4** [comment]
Finished HTML and CSS files for sustainability information (sustainable at home, sustainable at work, sustainable at school). 

we  uploaded files on s3 bucket, and link it to freenom domain. Freenom is domain provider.
www.ecopal.tk
