### ISSUE TITLE
Have a working prototype of our webpage for users to test (week 8)

### ISSUE THREAD

**Issue by wes-yang** [skl1m/ecopal#21]
A prototype of our website will be completed with most of the functionalities of our website
Have 5-10 users test our website and give us feedback

**Comment by skl1m** [comment]
So we did not create create a working prototype of our webpage for user to test by this point. So this task was technically not completed by week 8. It was fulfilled later on in the semester.

**Comment by mdpatel4** [comment]
As a Susan said we had basic layout for website, in which the s3 bucket link was linked to domain. Therefore, website was in online, but it was not fully implemented.
