### ISSUE TITLE
User testing of the whole system (week 11)

### ISSUE THREAD

**Issue by wes-yang** [skl1m/ecopal#26]
Have team members test and get feedback from at least 5 testers and discuss action plan

**Comment by skl1m** [comment]
Got our classmates to test our current system at the time. I created a google form for the testers to fill out after they were done. The form can be seen here:

https://docs.google.com/forms/d/e/1FAIpQLSdLv4B5knP15XVfW0ZRxjcGowGqHNlG0tJzq7W7tEafbBzgzA/viewform

We got 7 responses:
Dion
Jeffrey Tam
XINYI CHEN
Greg (WasteNot Team)
Austin Leavitt
good vibes
Harry Hoang

We got a lot of great feedback from the people who did test our system. They indicated the skill needed to be more interactive. 

~ 30 mins to create the form
