### ISSUE TITLE
Make changes, if any, based on feedback (week 13)

### ISSUE THREAD

**Issue by wes-yang** [skl1m/ecopal#30]
Have updated system working

**Comment by skl1m** [comment]
A feedback we got was to make the skill more conversational, looking into this:
https://developer.amazon.com/docs/custom-skills/dialog-interface-reference.html

Started looking into ways that I can have multiple ways of responding to the user opposed to saying the same thing each time an intent is started or the Alexa responds.

This task was completed.

~ 5 Hours

___________________________

Created a dbHelper.js file that handles all the database requests that the main index.js file uses.

~ 5 Hours

**Comment by wes-yang** [comment]
Remove initial utterance when starting Alexa skill
