### ISSUE TITLE
Work on presentation, finalize project documentation, meet to practice presentation (week 14)

### ISSUE THREAD

**Issue by wes-yang** [skl1m/ecopal#31]
Have an updated system, draft of presentation, rehearsed presentation as a group

**Comment by skl1m** [comment]
Susan: Made edits to the presentation.  ~ 1Hr
Made updates to the system ~ 24Hrs
Rehearsed presentation as a group ~ 2Hrs
Made updates to the user manual & dev guide. ~ 8Hrs
