### ISSUE TITLE
Search for new technologies for websites that use DynamoDB

### ISSUE THREAD

**Issue by wes-yang** [skl1m/ecopal#33]

**Comment by mdpatel4** [comment]
add information about different framework and platform for group suggestion on our google drive under the folder 491B >> MainFeatures
Time Dedication as of 9/24/18: 1 hour
Time Dedication as of 9/27/18: 3 hours

**Comment by mdpatel4** [comment]
I'm not able to find the framework that uses the DynamicDB database, so we'll finalize technology for web development end of this week.

**Comment by skl1m** [comment]
Between Angular/React

Reference:
https://medium.com/99xtechnology/full-stack-serverless-web-apps-with-aws-189d87da024a
