### ISSUE TITLE
Start fixing bugs in our Alexa system (week 3)

### ISSUE THREAD

**Issue by wes-yang** [skl1m/ecopal#7]
Major bug - after initial voice input, Alexa device continues to output utterances. Need to find all cases in which this bug occurs

**Comment by skl1m** [comment]
Will have a list of the current bugs, will link the google doc here: (TBA)

**Comment by skl1m** [comment]
This will be agaby's task and after her first go around I will be looking into this.

**Comment by skl1m** [comment]
This will be Agaby's task and after her first go around I will be looking into this.
______________________________________
- Sessions that are open will be reinvoked if random noises/sounds are uttered to the system:  Our classmate notified me that if Alexa does not recognize the utterance, it tries to match the correct intent. So this is not something that we can fix. 

- RecycleIntent had a bug , something to do with two-word items. This has not been fixed. Need to look into how to create two - three  word slots to handle this. Not done within the scope of this project. However, this is something I want to fix before I deploy the skill.
