### ISSUE TITLE
Go over the database schema as a team

### ISSUE THREAD

**Issue by wes-yang** [skl1m/ecopal#8]
Discuss all the tables we think we will need in our database and potential data for each table.

**Comment by skl1m** [comment]
Discussed today how we are going to implement a few new features Dr. Penzenstadler recommended. So Agaby's task this week is to add to the database schema and then Maulk will be helping this week with this.

At some point, I'll take a look at this as well. Probably by the end of this week.

**Comment by skl1m** [comment]
Plan on having this schema done by today?
